baseURL = "https://testzhupeng.netlify.com"
languageCode = "en-us"
paginate = 6
summaryLength = "10"
theme = "parsa-hugo"
title = "Parsa | Personal Blog Template"
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = "6 rip carl Avenue CA 90733"
author = "Themefisher"
author_image = "images/banner-img.png"
bio = "I’m a Freelance Interactive Art Director based in France. Focusing across branding and identity, digital and print."
contact_form_action = "#"
copyright = "Copyright &copy; 2020 a theme by [themefisher.com](themefisher.com)"
description = "This is meta description"
email = "exmaple@ymail.com"
google_analitycs_id = "Your ID"
home = "Home"
layout = "1"
logo = "images/logo.png"
mobile = "+90 000 333 22"
[params.instafeed]
access_token = "dd4c0e7c90625d517636619c23d57ad3"
enable = false
user_id = "633937037353857"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/headroom/headroom.js"
[[params.plugins.js]]
URL = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
URL = "plugins/masonry/masonry.js"
[[params.plugins.js]]
URL = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
URL = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"
[params.preloader]
enable = true
[params.search]
enable = true
[[params.social]]
URL = "#"
icon = "ti-facebook"
[[params.social]]
URL = "#"
icon = "ti-twitter-alt"
[[params.social]]
URL = "#"
icon = "ti-linkedin"
[[params.social]]
URL = "#"
icon = "ti-github"
